platform :ios, '5.0'

pod 'Appirater'
pod 'SVProgressHUD'
pod 'WCAlertView'

#pod 'SPThanksViewController', path: '..'
pod 'SPThanksViewController', git: 'https://github.com/tnantoka/SPThanksViewController.git'
